update

diff --git a/launcher/smartdock/smartdock-1121/EXTENSION b/launcher/smartdock/smartdock-1121/EXTENSION
--- a/launcher/smartdock/smartdock-1121/EXTENSION
+++ b/launcher/smartdock/smartdock-1121/EXTENSION
@@ -8,7 +8,7 @@ md5sums=("dde94e2babc5f78bf7279e60a98eef05")
 android_version=11
 
 package() {
-    case "$arch" in
+    case "$CARCH" in
         x86)
             mapped_arch="x86"
             bit=32
@@ -26,7 +26,7 @@ package() {
             bit=64
         ;;
         *)
-            echo "Error: Unknown architecture '$arch'" >&2
+            echo "Error: Unknown architecture '$CARCH'" >&2
             exit 1
         ;;
     esac
diff --git a/root/magisk-delta/magisk-delta-27001/EXTENSION b/root/magisk-delta/magisk-delta-27001/EXTENSION
--- a/root/magisk-delta/magisk-delta-27001/EXTENSION
+++ b/root/magisk-delta/magisk-delta-27001/EXTENSION
@@ -10,7 +10,7 @@ android_version=11
 
 package() {
     magisk_dir="$pkgdir/system/etc/init/magisk"
-    case "$arch" in
+    case "$CARCH" in
         x86)
             mapped_arch="x86"
             bit=32
@@ -28,7 +28,7 @@ package() {
             bit=64
         ;;
         *)
-            echo "Error: Unknown architecture '$arch'" >&2
+            echo "Error: Unknown architecture '$CARCH'" >&2
             exit 1
         ;;
     esac
